### ISSUE TITLE
Users and authentication

### ISSUE THREAD

**Issue by jaeming** [jaeming/RSVP#2]
We'll need users.  Users should have many events. Events should be public the but the list of guests should not only be available to the authenticated user who owns the event.

**Comment by jaeming** [comment]
A note: creating a guest for an event does not need to be authenticated.

**Comment by jaeming** [comment]
I'll take this on right now and get devise added.

**Comment by salexzee** [comment]
Is this basically going to be the only people who are users are the people who make events? Or are guests going to also have to log in? I'm thinking a guest should be similar to someone who is subscribed to a mailing list or blog. They get all the updates emailed to them of a specific event, but they're not actually a member of the site.

**Comment by salexzee** [comment]
Maybe I should have read the first comment a second time lol

**Comment by jaeming** [comment]
;)
