### ISSUE TITLE
Alter Events List Page

### ISSUE THREAD

**Issue by salexzee** [jaeming/RSVP#8]
I'm thinking that there shouldn't be a page that lists out all events. Most events people ask for RSVP's for aren't really open to the general public. I'm thinking it should be a search bar and you can look up an event by name, type of event, host and whatever else would be helpful. That way if someone doesn't currently have the link handy, they can search for the event. People should also probably have the option to have their event be private so that people can't search for it.

**Comment by jaeming** [comment]
Agreed. Index is unnecessary. They should have a shared link or like you said, fall back on a search.
Maybe we could make index reflect just a user's events:
`@events = current_user.events`
so when you go to index, you only see your own events or if not a user, you'll see either nothing or a search box.

**Comment by salexzee** [comment]
That sounds good.
